ROLE_SUPER_ADMIN = "super_admin"
ROLE_SITE_ADMIN = "site_admin"
ROLE_COMPANY_OWNER = "company_owner"
ROLE_COMPANY_ADMIN = "company_admin"
ROLE_TERMINAL_USER = "terminal_user"
ROLE_EMPLOYEE = "employee"


PLATFORM_ROLES = {
    ROLE_SUPER_ADMIN,
    ROLE_SITE_ADMIN,
}

COMPANY_ROLES = {
    ROLE_COMPANY_OWNER,
    ROLE_COMPANY_ADMIN,
}

TERMINAL_ROLES = {
    ROLE_TERMINAL_USER,
}

EMPLOYEE_ROLES = {
    ROLE_EMPLOYEE,
}

ALL_ROLES = (
    PLATFORM_ROLES
    | COMPANY_ROLES
    | TERMINAL_ROLES
    | EMPLOYEE_ROLES
)
