ROLE_SUPER_ADMIN = "super_admin"
ROLE_SITE_ADMIN = "site_admin"
ROLE_COMPANY_OWNER = "company_owner"
ROLE_COMPANY_ADMIN = "company_admin"
ROLE_TERMINAL_USER = "terminal_user"
ROLE_EMPLOYEE = "employee"

PERM_MANAGE_PLATFORM = "manage_platform"
PERM_VIEW_DASHBOARD = "view_dashboard"
PERM_MANAGE_EMPLOYEES = "manage_employees"
PERM_VIEW_REPORTS = "view_reports"
PERM_USE_TERMINAL = "use_terminal"
PERM_MANAGE_USERS = "manage_users"
PERM_MANAGE_LOCATIONS = "manage_locations"
PERM_MANAGE_TERMINALS = "manage_terminals"
PERM_MANAGE_COMPANY_SETTINGS = "manage_company_settings"


PLATFORM_ROLES = {
    ROLE_SUPER_ADMIN,
    ROLE_SITE_ADMIN,
}

COMPANY_ROLES = {
    ROLE_COMPANY_OWNER,
    ROLE_COMPANY_ADMIN,
}

TERMINAL_ROLES = {
    ROLE_TERMINAL_USER,
}

EMPLOYEE_ROLES = {
    ROLE_EMPLOYEE,
}

ALL_ROLES = (
    PLATFORM_ROLES
    | COMPANY_ROLES
    | TERMINAL_ROLES
    | EMPLOYEE_ROLES
)

COMPANY_WORKSPACE_ROLES = PLATFORM_ROLES | COMPANY_ROLES
USER_MANAGEMENT_ROLES = PLATFORM_ROLES | COMPANY_ROLES
TERMINAL_ACCESS_ROLES = PLATFORM_ROLES | COMPANY_ROLES | TERMINAL_ROLES

ROLE_PERMISSIONS = {
    ROLE_SUPER_ADMIN: {
        PERM_MANAGE_PLATFORM,
        PERM_VIEW_DASHBOARD,
        PERM_MANAGE_EMPLOYEES,
        PERM_VIEW_REPORTS,
        PERM_USE_TERMINAL,
        PERM_MANAGE_USERS,
        PERM_MANAGE_LOCATIONS,
        PERM_MANAGE_TERMINALS,
        PERM_MANAGE_COMPANY_SETTINGS,
    },
    ROLE_SITE_ADMIN: {
        PERM_MANAGE_PLATFORM,
        PERM_VIEW_DASHBOARD,
        PERM_MANAGE_EMPLOYEES,
        PERM_VIEW_REPORTS,
        PERM_USE_TERMINAL,
        PERM_MANAGE_USERS,
        PERM_MANAGE_LOCATIONS,
        PERM_MANAGE_TERMINALS,
        PERM_MANAGE_COMPANY_SETTINGS,
    },
    ROLE_COMPANY_OWNER: {
        PERM_VIEW_DASHBOARD,
        PERM_MANAGE_EMPLOYEES,
        PERM_VIEW_REPORTS,
        PERM_USE_TERMINAL,
        PERM_MANAGE_USERS,
        PERM_MANAGE_LOCATIONS,
        PERM_MANAGE_TERMINALS,
        PERM_MANAGE_COMPANY_SETTINGS,
    },
    ROLE_COMPANY_ADMIN: {
        PERM_VIEW_DASHBOARD,
        PERM_MANAGE_EMPLOYEES,
        PERM_VIEW_REPORTS,
        PERM_USE_TERMINAL,
        PERM_MANAGE_LOCATIONS,
        PERM_MANAGE_TERMINALS,
        PERM_MANAGE_COMPANY_SETTINGS,
    },
    ROLE_TERMINAL_USER: {
        PERM_USE_TERMINAL,
    },
    ROLE_EMPLOYEE: set(),
}
